#  Algoritmo WaveFront
# Vecindad de Neumann y Moore
# Leonardo David Monsalvo Camacho - T00047540

In [1]:
import random 
import numpy as np
import os

## Creación de la matriz y restricciones de sus parametros

In [2]:
def creaMatriz():
    
    #Creamos una matriz de orden 4x5 rellenada con 0 y obstaculos en -1
    matriz = np.random.randint(low = 1, size =(4, 5)) 
    matriz[2][3] = -1
    matriz[1][3] = -1
    matriz[1][2] = -1
    matriz[3][3] = -1

    return (matriz)

def condiciones():
    
    #Petición de las posiciones iniciales y finales para el robot (filas y columnas)
    Ifila = int(input("Fila posición inicial: "))
    Icol = int(input("Columna posición inicial: "))
    Ffila = int(input("Fila posición final: "))
    Fcol = int (input("Columna posición final: "))
    
    #Se condiciona para que el usuario ingrese números validos, posiciones no asignadas y rangos permitidos
    while ((Ifila or Ffila) > matriz.shape[0]-1 or (Ifila == Ffila and Icol == Fcol) or (Icol or Fcol) > matriz.shape[1]-1 or (matriz[Ifila][Icol] or matriz[Ffila][Fcol]) == -1):
        
        #matriz.shape es usado para obtener las dimensiones de la matriz de una forma más dinámica 
        print ("Es una matriz ", matriz.shape[0],"x", matriz.shape[1])
        print ("¡Fuera de rango, obstaculo o posición igual!!!")
        Ifila = int(input("\nFila posición inicial: "))
        Icol = int(input("Columna posición inicial: "))
        Ffila = int(input("Fila posición final: "))
        Fcol = int(input("Columna posición final: "))
    
    print ("\nMatriz Original\n", matriz)
    
    #Si toda la matriz está llena de 0, procedemos a introducir nuestro indice de arranque
    if (matriz.all() == 0):

        matriz[Ffila][Fcol] = 1
    
    #Retornamos los valores que más adelante necesitaremos.
    aux1, aux2 = Ffila, Fcol
    return Ifila, Icol, Ffila, Fcol, matriz, aux1, aux2

## Complejidad, análisis y lógica para el desarrollo del algoritmo

In [3]:
#Pasamos como parametros los valores que previamente retornamos
def Vecindades(Ifila, Icol, Ffila, Fcol, opcion, aux1, aux2):

    posx = []
    posy = []
    aux = 1
    x = 0
    
    #For anidado para recorrer la matriz e ir haciendo los movimientos con el "Robot"
    for i in range (matriz.shape[0]):

        for j in range (matriz.shape[1]):
            #Se inicia el algoritmo para Neuman y Moore de manera condicionada
            if (opcion == 1 or opcion == 2):
                while (matriz[Ifila][Icol] == 0):

                    #Guardo mi posición actual en mis posiciones finales y aumento en 1
                    if(aux==0):
                        Ffila= posx[x]
                        Fcol= posy[x]
                        x += 1

                    aux = 0
                    
                    #Este contador me guarda la posición actual para cuando vaya avanzando los valores vayan cambiando
                    #Aumentando en 1
                    cont = matriz[Ffila][Fcol]
                    
                    #Mueve hacía arriba
                    if(Ffila > 0):    
                        if(matriz[Ffila-1][Fcol]==0):          
                            matriz[Ffila-1][Fcol]= cont +1 
                            posx.append(Ffila-1)
                            posy.append(Fcol)             
                            os.system("clear")
                            print("\n")
                            print(matriz)
                    
                    #Mueve hacía zquierda
                    if(Fcol > 0 ): 
                        if(matriz[Ffila][Fcol-1]==0):
                            matriz[Ffila][Fcol-1]= cont + 1
                            posx.append(Ffila)
                            posy.append(Fcol-1)
                            os.system("clear")
                            print("\n")
                            print(matriz)
                    
                    #Mueve hacía derecha
                    if(Fcol < matriz.shape[1]-1):
                        if(matriz[Ffila][Fcol+1]==0):
                            matriz[Ffila][Fcol+1]= cont + 1
                            posx.append(Ffila)
                            posy.append(Fcol+1)
                            os.system("clear")
                            print("\n")
                            print(matriz)
                            
                    #Mueve hacía abajo
                    if(Ffila < matriz.shape[0]-1):
                        if(matriz[Ffila+1][Fcol]==0):
                            matriz[Ffila+1][Fcol]= cont + 1
                            posx.append(Ffila+1)
                            posy.append(Fcol)
                            os.system("clear")
                            print("\n")
                            print(matriz)

                    
                    #La vecindad de Moore además de moverse en diagonales, también puede hacerlo como Neumann
                    #Es por ello que la vecindad de Moore toma como parametros iniciales las propiedades de Neumann
                    #Pero que llegadas a las diagonales solo es posible para moore
                    if (opcion == 2):
                        
                        #Mueve hacía arriba derecha
                        if(Ffila > 0 and Fcol < matriz.shape[1]-1 ):
                            if(matriz[Ffila-1][Fcol+1]==0):
                                matriz[Ffila-1][Fcol+1]= cont + 1
                                posx.append(Ffila-1)
                                posy.append(Fcol+1)
                                os.system("clear")
                                print("\n")
                                print(matriz)
                        
                        #Mueve hacía arriba izquierda
                        if(Ffila > 0 and Fcol > 0 ):
                            if(matriz[Ffila-1][Fcol-1]==0):
                                matriz[Ffila-1][Fcol-1]= cont + 1
                                posx.append(Ffila-1)
                                posy.append(Fcol-1)
                                os.system("clear")
                                print("\n")
                                print(matriz)
                        
                        #Mueve hacía abajo derecha
                        if(Ffila<matriz.shape[0]-1 and Fcol<matriz.shape[1]-1 ):
                            if(matriz[Ffila+1][Fcol+1]==0):
                                matriz[Ffila+1][Fcol+1]= cont + 1
                                posx.append(Ffila+1)
                                posy.append(Fcol+1)
                                os.system("clear")
                                print("\n")
                                print(matriz)
                        
                        #Mueve hacía abajo izquierda
                        if(Ffila < matriz.shape[0]-1 and Fcol > 0 ):
                            if(matriz[Ffila+1][Fcol-1]==0):
                                matriz[Ffila+1][Fcol-1]= cont + 1
                                posx.append(Ffila+1)
                                posy.append(Fcol-1)
                                os.system("clear")
                                print("\n")
                                print(matriz)
                
                #Encuentra la ruta más óptima para cada vecindad
                if (opcion == 1 or opcion == 2):

                    llegada = matriz[Ffila][Fcol]
                    partida = matriz[Ifila][Icol]

                    Ffila, Fcol = aux1, aux2
                    x = []
                    y = []

                    while (llegada != partida):

                        partida -= 1
                        #Mueve hacía abajo
                        if(Ifila<matriz.shape[0]-1):
                            if(matriz[Ifila+1][Icol]==partida):
                                Ifila += 1
                                Icol=Icol
                                x.append(Ifila)
                                y.append(Icol)
                                continue
                        
                        #Mueve hacía arriba
                        if(Ifila>0):
                            if(matriz[Ifila-1][Icol]==partida):
                                Ifila += -1
                                Icol=Icol
                                x.append(Icol)
                                y.append(Icol)
                                continue
                                
                        #Mueve hacía derecha
                        if(Icol<matriz.shape[1]-1):
                            if(matriz[Ifila][Icol+1]==partida):
                                Ifila=Ifila
                                Icol += 1
                                x.append(Ifila)
                                y.append(Icol)
                                continue
                        
                        #Mueve hacía izquierda
                        if(Icol>0):
                            if(matriz[Ifila][Icol-1]==partida):
                                Ifila=Ifila
                                Icol += -1
                                x.append(Ifila)
                                y.append(Icol)
                                continue
                        
                        #Es la misma condición que se explico al principio, donde moore usa partes de neumann pero no 
                        #Al contrario
                        if (opcion == 2):
                            
                            #Mueve arriba-izquierda
                            if(Ifila>0 and Icol>0):
                                if(matriz[Ifila-1][Icol-1]==partida):
                                    Ifila=Ifila-1
                                    Icol=Icol-1
                                    x.append(Ifila)
                                    y.append(Icol)
                                    continue
                            
                            #Mueve arriba-derecha
                            if(Ifila > 0 and Icol<matriz.shape[1]-1 ):
                                if(matriz[Ifila-1][Icol+1]==partida):
                                    Ifila=Ifila-1
                                    Icol=Icol+1
                                    x.append(Ifila)
                                    y.append(Icol)
                                    continue
                                    
                            #Mueve abajo-izquierda
                            if(Ifila < matriz.shape[0]-1 and Icol > 0 ):
                                if(matriz[Ifila+1][Icol-1]==partida):
                                    Ifila=Ifila-1
                                    Icol=Icol-1
                                    x.append(Ifila)
                                    y.append(Ifila)
                                    continue
                            
                            #Mueve abajo-derecha
                            if(Ifila<matriz.shape[0]-1 and Icol<matriz.shape[1]-1 ):
                                if(matriz[Ifila+1][Icol+1]==partida):
                                    Ifila=Ifila+1
                                    Icol=Icol+1
                                    x.append(Ifila)
                                    y.append(Icol) 
                                    continue
                
                for l in range (len(x)):
                    print ("\nRuta:  (",x[l]," , ", y[l],")")

# Implementación de Menú para organizar todo visualmente

In [4]:
#Función para pedir numero y que sea validado para las opciones disponibles
def pedirNumeroEntero():
     
    correcto=False
    num=0
    while(not correcto):
        try:
            num = int(input("Introduce un numero entero: "))
            correcto=True
        except ValueError:
            print('Error, introduce un numero entero')
     
    return num
 
salir = False
opcion = 0
 
while not salir:
    print ("\n")
    print ("1. John von Vecindades")
    print ("2. Edward Forrest Moore")
    print ("3. Salir")
     
    print ("Elige una opcion")
     
    #Instanciamiento
    opcion = pedirNumeroEntero()
 
    if opcion == 1:
        print ("")
        
        #Instanciar 
        matriz = creaMatriz()
        Ifila, Icol, Ffila, Fcol, matriz, aux1, aux2 = condiciones()
        print ("\nMatriz iniciada\n {}\n".format(matriz))
        print ("\n\t\t******Vecindad de Neumann******")
        Vecindades(Ifila, Icol, Ffila, Fcol, opcion,aux1, aux2)

    elif opcion == 2:
        print("")
        
        #Instanciar
        matriz = creaMatriz()
        Ifila, Icol, Ffila, Fcol, matriz, aux1, aux2 = condiciones()
        print ("\nMatriz iniciada\n {}\n".format(matriz))
        print ("\n\t\t******Vecindad de Moore******")
        Vecindades(Ifila, Icol, Ffila, Fcol, opcion,aux1, aux2)

    elif opcion == 3:
        salir = True
    else:
        print ("Introduce un numero entre 1 y 3")



1. John von Vecindades
2. Edward Forrest Moore
3. Salir
Elige una opcion
Introduce un numero entero: 1

Fila posición inicial: 3
Columna posición inicial: 2
Fila posición final: 3
Columna posición final: 4

Matriz Original
 [[ 0  0  0  0  0]
 [ 0  0 -1 -1  0]
 [ 0  0  0 -1  0]
 [ 0  0  0 -1  0]]

Matriz iniciada
 [[ 0  0  0  0  0]
 [ 0  0 -1 -1  0]
 [ 0  0  0 -1  0]
 [ 0  0  0 -1  1]]


		******Vecindad de Neumann******


[[ 0  0  0  0  0]
 [ 0  0 -1 -1  0]
 [ 0  0  0 -1  2]
 [ 0  0  0 -1  1]]


[[ 0  0  0  0  0]
 [ 0  0 -1 -1  3]
 [ 0  0  0 -1  2]
 [ 0  0  0 -1  1]]


[[ 0  0  0  0  4]
 [ 0  0 -1 -1  3]
 [ 0  0  0 -1  2]
 [ 0  0  0 -1  1]]


[[ 0  0  0  5  4]
 [ 0  0 -1 -1  3]
 [ 0  0  0 -1  2]
 [ 0  0  0 -1  1]]


[[ 0  0  6  5  4]
 [ 0  0 -1 -1  3]
 [ 0  0  0 -1  2]
 [ 0  0  0 -1  1]]


[[ 0  7  6  5  4]
 [ 0  0 -1 -1  3]
 [ 0  0  0 -1  2]
 [ 0  0  0 -1  1]]


[[ 8  7  6  5  4]
 [ 0  0 -1 -1  3]
 [ 0  0  0 -1  2]
 [ 0  0  0 -1  1]]


[[ 8  7  6  5  4]
 [ 0  8 -1 -1  3]
 [ 0  0  0 